_target_: models.models.multi_level_vqvae.decoder.AttentionStftDecoder
input_dim: 512
num_heads: 16
hidden_dim: 512
num_layers: 6
n_fft: 256
hop_length: 64 # Must be equal to the sequence length reduction ration in the encoder divided by the expansion factor
win_length: 256
expansion_factor: 8
dropout: 0.1
padding: same