_target_: models.models.multi_level_vqvae.decoder.Decoder1D
channel_list: [8, 512, 256, 128, 64, 32, 16]
dim_change_list: [2, 2, 2, 2, 2, 2]
input_channels: 1
kernel_size: 3
dim_add_kernel_add: 0
num_res_block_conv: 5
dilation_factor: 3
activation_fn:
  _target_: torch.nn.GELU