_target_: models.models.multi_level_vqvae.decoder.StftDecoder1D
channel_list: [512, 1024, 512, 256, 128]
dim_change_list: [2, 2, 2, 2]
input_channels: 1
kernel_size: 7
dim_add_kernel_add: 0
num_res_block_conv: 5
dilation_factor: 3
activation_fn:
  _target_: torch.nn.GELU
dropout: 0.13

# STFT parameters
n_fft: 128
hop_length: 32
win_length: 128
# Sequence length must be latent_size * hop_length * prod(dim_change_list)