_target_: models.models.multi_level_vqvae.decoder.RippleDecoder
activation:
  _target_: torch.nn.LeakyReLU
  negative_slope: 0.1
dec_params:
  _target_: models.models.multi_level_vqvae.decoder.ripple.RippleDecoderParameters
  input_dim: 8192 # Needs to be token_dim * num tokens in sequence
  hidden_dim: 256
  mlp_num_layers: 3
  output_dim: 32768
  ripl_hidden_dim: 64
  ripl_num_layers: 3
  ripl_coordinate_multiplier: 1