# Model type
type: atn_token_predictor
module_type: music

# Model parameters
hidden_size: 48
latent_depth: 64
channel_dim_change_list: [4, 4, 4, 4]
input_channels: 1
conv_out_channels: 1
vocabulary_size: 1024
num_codebooks: 8
num_res_block_conv: 4
dilation_factor: 3
activation_type: relu

# Encoder parameters
encoder_kernel_size: 3
encoder_dim_change_kernel_size: 3

# Decoder parameters
slice_length: 256
decoder:
  hidden_dim: 256
  num_encoders: 2
  num_decoders: 3
  num_heads: 4
  