type: chaos_hydra
module_type: autoregressor

# Mamba parameters
vocabulary_size: 1024
model_dim: 192
ssm_state_dim: 16
conv_width: 3
expansion: 2

# Chaos hydra parameters
num_heads: 16
mlp_head:
  hidden_dim: 32
  num_layers: 3
  activation: leaky_relu