defaults:
  - _self_
  - feature_extractor: encoder1d_random_long
  - class_head: mlp_2c

_target_: models.models.discriminator.AttentionEmbeddingEncoder
hidden_dim: 512
num_heads: 8
num_layers: 6
dropout: 0.1
