defaults:
  - _self_
  - encoder: encoder1d_lvl2
  - decoder: decoder1d_lvl2

_target_: models.models.multi_level_vqvae.ml_vqvae.EmbeddingMlVqvae
input_channels: 16
outer_vocab_size: 2048
vq_module:
  _target_: models.models.multi_level_vqvae.blocks.VQ1D
  token_dim: 512
  num_tokens: 1024
  num_rq_steps: 4
loss_aggregator: ${loss.aggregator}