defaults:
  - _self_
  - encoder: encoder1d
  - decoder: decoder1d

_target_: models.models.multi_level_vqvae.ml_vqvae.MultiLvlVQVariationalAutoEncoder
input_channels: 1
vq_module:
  _target_: models.models.multi_level_vqvae.blocks.VQ1D
  token_dim: 256
  num_tokens: 1024
  num_rq_steps: 4
loss_aggregator: ${loss.aggregator}