defaults:
  - _self_
  - encoder: encoder1d_small
  - decoder: decoder1d_small

_target_: models.models.multi_level_vqvae.ml_vqvae.MultiLvlVQVariationalAutoEncoder
input_channels: 1
vq_module:
  _target_: models.models.multi_level_vqvae.blocks.VQ1D
  token_dim: 128
  num_tokens: 1024
  num_rq_steps: 4
loss_aggregator: ${loss.aggregator}