# Model type
type: multi_lvl_vqvae
module_type: music

# Model parameters
hidden_size: 32
latent_depth: 16
channel_dim_change_list: [4, 4, 4, 4, 4]
input_channels: 1
vocabulary_size: 2048
num_codebooks: 4
num_res_block_conv: 4
dilation_factor: 3
activation_type: relu

# Encoder and decoder parameters
encoder_kernel_size: 3
encoder_dim_change_kernel_size: 3
decoder_kernel_size: 3
decoder_dim_change_kernel_add: 0
