# Model type
type: multi_lvl_vqvae
module_type: music

# Model parameters
hidden_size: 48
latent_depth: 16
channel_dim_change_list: [2, 2, 4, 16]
input_channels: 1
vocabulary_size: 1024
num_codebooks: 4
num_res_block_conv: 3
dilation_factor: 3
activation_type: relu

# Encoder and decoder parameters
encoder_kernel_size: 3
encoder_dim_change_kernel_size: 3
decoder_kernel_size: 3
decoder_dim_change_kernel_add: 0
