# Model type
type: ripl_vqvae
module_type: music

# Model parameters
hidden_size: 4
latent_depth: 128
channel_dim_change_list: [2, 2, 2, 2, 2, 2, 2, 2]
input_channels: 1
vocabulary_size: 4092
num_codebooks: 1
num_res_block_conv: 4
dilation_factor: 3
activation_type: gelu

# Encoder parameters
encoder_kernel_size: 3
encoder_dim_change_kernel_size: 3

# Decoder parameters
input_size: 1024
decoder_params:
  hidden_dim: 1024
  mlp_num_layers: 3
  ripl_hidden_dim: 32
  ripl_num_layers: 3
