# Model type
type: ripl_vqvae
module_type: music

# Model parameters
hidden_size: 32
latent_depth: 16
channel_dim_change_list: [2, 2, 4, 16]
input_channels: 1
vocabulary_size: 1024
num_codebooks: 4
num_res_block_conv: 3
dilation_factor: 3
activation_type: relu

# Encoder parameters
encoder_kernel_size: 3
encoder_dim_change_kernel_size: 3

# Decoder parameters
input_size: 256
decoder_params:
  hidden_dim: 1024
  mlp_num_layers: 2
  ripl_hidden_dim: 32
  ripl_num_layers: 3
  ripl_coordinate_multipler: 10
