_target_: models.models.diffusion.TokenDiffusionTransformer
vocab_size: 8192 # Should be equal to the codebook size
cond_size: 53 # Should be equal to the number of datapoints
hidden_size: 512
num_layers: 6
num_heads: 8
dropout: 0.1