# Model type
type: token_predictor
module_type: music

# Model parameters
hidden_size: 48
latent_depth: 64
channel_dim_change_list: [4, 4, 4, 4]
input_channels: 1
conv_out_channels: 32
vocabulary_size: 256
num_codebooks: 4
num_res_block_conv: 4
dilation_factor: 3
activation_type: relu

# Encoder and decoder parameters
encoder_kernel_size: 3
encoder_dim_change_kernel_size: 3
decoder_kernel_size: 3
decoder_dim_change_kernel_add: 0