- _target_: loss.components.BasicClassificationLoss
  name: ce_loss
  weight: 1.0
  pred_key: logits
  ref_key: class
  base_loss:
    _target_: torch.nn.CrossEntropyLoss

- _target_: loss.components.PercentCorrect
  name: percent_correct
  weights: 0.0
  pred_key: logits
  ref_key: class
  