reconstruction_loss:
  type: rec
  weight: 0.1
  base_loss: 'mse'
  phase_parameter: 1

edge_reconstruction_loss:
  type: edge_rec
  weight: 0.1
  base_loss: "mse"
  edge_power: 3.0

alignment_loss:
  type: align
  weight: 0.5
  base_loss: 'mse'

commitment_loss:
  type: commit
  weight: 0.5
  base_loss: 'mse'

melspec_loss_1:
  type: mel_spec
  weight: 3.0
  base_loss: 'mse'
  lin_start: 1.00
  lin_end: 1.0
  
  melspec_params:
    n_fft: 256
    f_min: 0
    hop_length: 64
    n_mels: 32
    pad_mode: reflect
    power: 2.0
    norm: "slaney"
    mel_scale: "htk"
    pad: 0

melspec_loss_2:
  type: mel_spec
  weight: 3.0
  base_loss: 'l1'
  lin_start: 1.0
  lin_end: 1.0

  melspec_params:
    n_fft: 128
    f_min: 0
    hop_length: 32
    n_mels: 32
    pad_mode: reflect
    power: 2.0
    norm: "slaney"
    mel_scale: "htk"
    pad: 0

melspec_loss_3:
  type: mel_spec
  weight: 3.0
  base_loss: 'l1'
  lin_start: 0.1
  lin_end: 200

  melspec_params:
    n_fft: 128
    f_min: 0
    hop_length: 32
    n_mels: 16
    pad_mode: reflect
    power: 1.0
    norm: "slaney"
    mel_scale: "htk"
    pad: 0

melspec_loss_4:
  type: mel_spec
  weight: 5.0
  base_loss: 'mse'
  lin_start: 0.1
  lin_end: 200.0
  
  melspec_params:
    n_fft: 256
    f_min: 0
    hop_length: 64
    n_mels: 32
    pad_mode: reflect
    power: 1.0
    norm: "slaney"
    mel_scale: "htk"
    pad: 0

melspec_loss_5:
  type: mel_spec
  weight: 5.0
  base_loss: 'l1'
  lin_start: 0.5
  lin_end: 10.0

  melspec_params:
    n_fft: 128
    f_min: 0
    hop_length: 64
    n_mels: 16
    pad_mode: reflect
    power: 2.0
    norm: "slaney"
    mel_scale: "htk"
    pad: 0