- _target_: loss.components.RecLoss
  name: rec
  weight: 1.0
  pred_key: slice
  ref_key: slice
  base_loss:
    _target_: torch.nn.L1Loss

- _target_: loss.components.RecLoss
  name: high_pass_rec
  weight: 5.0
  pred_key: slice
  ref_key: slice
  base_loss:
    _target_: torch.nn.L1Loss
  transform_func:
    _target_: utils.transform_func.high_pass_filter
    cutoff: 1000.0
    _partial_: True

- _target_: loss.components.reconstruction.EdgeRecLoss
  name: edge_rec
  weight: 1.0
  pred_key: slice
  ref_key: slice
  edge_power: 3.0
  base_loss:
    _target_: torch.nn.L1Loss

- _target_: loss.components.AlignLoss
  name: alignment_loss
  weight: 0.5
  base_loss:
    _target_: torch.nn.MSELoss

- _target_: loss.components.CommitLoss
  name: commitment_loss
  weight: 0.5
  base_loss:
    _target_: torch.nn.MSELoss

- _target_: loss.components.DiscriminatorHingeLoss
  name: discriminator_loss
  weight: 10.0
  pred_key_real: d_input
  pred_key_fake: d_output