- _target_: loss.components.RecLoss
  name: rec_l2
  weight: 0.3
  pred_key: slice
  ref_key: slice
  base_loss:
    _target_: torch.nn.MSELoss

- _target_: loss.components.RecLoss
  name: rec_2500
  weight: 2.0
  pred_key: slice
  ref_key: slice
  base_loss:
    _target_: torch.nn.MSELoss
  transform_func:
    _target_: utils.transform_func.high_pass_filter
    cutoff: 2500.0
    _partial_: True

- _target_: loss.components.RecLoss
  name: rec_5000
  weight: 5.0
  pred_key: slice
  ref_key: slice
  base_loss:
    _target_: torch.nn.MSELoss
  transform_func:
    _target_: utils.transform_func.high_pass_filter
    cutoff: 5000.0
    _partial_: True

- _target_: loss.components.RecLoss
  name: rec_10k
  weight: 10.0
  pred_key: slice
  ref_key: slice
  base_loss:
    _target_: torch.nn.MSELoss
  transform_func:
    _target_: utils.transform_func.high_pass_filter
    cutoff: 10000.0
    _partial_: True

- _target_: loss.components.reconstruction.EdgeRecLoss
  name: edge_rec
  weight: 1.0
  pred_key: slice
  ref_key: slice
  edge_power: 3.0
  base_loss:
    _target_: torch.nn.MSELoss

- _target_: loss.components.AlignLoss
  name: alignment_loss
  weight: 0.5
  base_loss:
    _target_: torch.nn.MSELoss

- _target_: loss.components.CommitLoss
  name: commitment_loss
  weight: 0.5
  base_loss:
    _target_: torch.nn.MSELoss

- _target_: loss.components.MelSpecLoss
  name: melspec_loss_1
  weight: 1.0
  base_loss:
    _target_: torch.nn.L1Loss
  lin_start: 1.0
  lin_end: 1.0
  pred_key: slice
  ref_key: slice
  transform_func: 
    _target_: utils.transform_func.log_normal_fixed
    _partial_: true
    mean: -5
    std: 4.7
  mel_spec_converter:
    _target_: models.mel_spec_converters.SimpleMelSpecConverter
    mel_spec_params: 
      _target_: utils.containers.MelSpecParameters
      n_fft: 2048
      f_min: 0
      hop_length: 512
      n_mels: 128
      pad_mode: reflect
      power: 2.0
      norm: slaney
      mel_scale: htk
      pad: 0

- _target_: loss.components.MelSpecLoss
  name: melspec_loss_2
  weight: 1.0
  base_loss:
    _target_: torch.nn.L1Loss
  lin_start: 1.0
  lin_end: 1.0
  pred_key: slice
  ref_key: slice
  mel_spec_converter:
    _target_: models.mel_spec_converters.SimpleMelSpecConverter
    mel_spec_params: 
      _target_: utils.containers.MelSpecParameters
      n_fft: 1024
      f_min: 0
      hop_length: 256
      n_mels: 64
      pad_mode: reflect
      power: 2.0
      norm: slaney
      mel_scale: htk
      pad: 0

- _target_: loss.components.MelSpecLoss
  name: melspec_loss_3
  weight: 1.0
  base_loss:
    _target_: torch.nn.L1Loss
  lin_start: 0.1
  lin_end: 20
  pred_key: slice
  ref_key: slice
  mel_spec_converter:
    _target_: models.mel_spec_converters.SimpleMelSpecConverter
    mel_spec_params: 
      _target_: utils.containers.MelSpecParameters
      n_fft: 512
      f_min: 0
      hop_length: 128
      n_mels: 32
      pad_mode: reflect
      power: 1.0
      norm: slaney
      mel_scale: htk
      pad: 0

- _target_: loss.components.MelSpecLoss
  name: melspec_loss_4
  weight: 5.0
  base_loss:
    _target_: torch.nn.L1Loss
  lin_start: 0.5
  lin_end: 10.0
  transform_func: 
    _target_: utils.transform_func.log_normal_fixed
    _partial_: true
    mean: -5
    std: 4.7
  pred_key: slice
  ref_key: slice
  mel_spec_converter:
    _target_: models.mel_spec_converters.SimpleMelSpecConverter
    mel_spec_params: 
      _target_: utils.containers.MelSpecParameters
      n_fft: 4096
      f_min: 0
      hop_length: 1024
      n_mels: 256
      pad_mode: reflect
      power: 1.0
      norm: slaney
      mel_scale: htk
      pad: 0


- _target_: loss.components.MelSpecLoss
  name: melspec_loss_5
  weight: 5.0
  base_loss:
    _target_: torch.nn.L1Loss
  lin_start: 0.1
  lin_end: 20.0
  pred_key: slice
  ref_key: slice
  mel_spec_converter:
    _target_: models.mel_spec_converters.SimpleMelSpecConverter
    mel_spec_params: 
      _target_: utils.containers.MelSpecParameters
      n_fft: 512
      f_min: 0
      hop_length: 256
      n_mels: 64
      pad_mode: reflect
      power: 2.0
      norm: slaney
      mel_scale: htk
      pad: 0