- _target_: loss.components.LLMClassificationLoss
  name: basic_cls
  weight: 1.0
  pred_key: logits
  ref_key: latent indices
  base_loss:
    _target_: torch.nn.CrossEntropyLoss

- _target_: loss.components.LLMPercentCorrect
  name: percent_correct
  weight: 0.0
  pred_key: logits
  ref_key: latent indices

- _target_: loss.components.AlignLoss
  name: align
  weight: 0.5
  base_loss:
    _target_: torch.nn.MSELoss

- _target_: loss.components.CommitLoss
  name: commit
  weight: 0.5
  base_loss:
    _target_: torch.nn.MSELoss