_target_: models.models.multi_level_vqvae.encoder.Encoder1D
channel_list: [2, 4, 8, 16, 32, 64, 8]
dim_change_list: [2, 2, 4, 4, 4, 4]
input_channels: 1
kernel_size: 3
num_res_block_conv: 5
dilation_factor: 3
activation_fn: 
  _target_: torch.nn.LeakyReLU
  negative_slope: 0.1
