_target_: models.models.multi_level_vqvae.encoder.Encoder1D
channel_list: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512]
dim_change_list: [2, 2, 2, 2, 2, 2, 2, 2, 2]
input_channels: 1
kernel_size: 3
dim_change_kernel_size: 3
num_res_block_conv: 5
dilation_factor: 3
activation_fn: 
  _target_: torch.nn.GELU
