defaults:
  - scheduler: "none"
  - optimizer: "none"

learning_rate: 0.0001
weight_decay: 0.0001
batch_size: 1024
epochs: 1000
beta_ema: 0.0
gradient_clip: 0.5
val_split: 0.001
test_split: 0.0
amp: False
num_devices: 0
num_workers: 11
save_path: "saved/"

# Scheduler config basic
interval: "epoch"
loss_monitor: "validation total loss"
frequency: 1
