defaults:
  - scheduler: "onecyclelr"
  - optimizer: "none"

learning_rate: 0.0003
weight_decay: 0.02
batch_size: 128
epochs: 350
beta_ema: 0.9999
gradient_clip: 0.1
val_split: 0.01
test_split: 0.0
amp: False
num_devices: 0
num_workers: 4
save_path: "saved/"

# Scheduler config basic
interval: "step"
loss_monitor: "validation total loss"
frequency: 1