defaults:
  - scheduler: "none"
  - optimizer: "none"

learning_rate: 0.0001
weight_decay: 0.002
batch_size: 32
epochs: 500
beta_ema: 0.9999
gradient_clip: 0.1
val_split: 0.001
test_split: 0.0
amp: False
num_devices: 0
num_workers: 11
save_path: "saved/"

# Scheduler config basic
interval: "epoch"
loss_monitor: "validation total loss"
frequency: 1
