# Target for learning params object
_target_: utils.learning.LearningParameters

# Echo model name
model_name: ${model_name}

# Learning parameters
learning_rate: 0.0005
weight_decay: 0.0
batch_size: 64
grad_accumulation: 1
epochs: 10000
beta_ema: 0.99
gradient_clip: null # Do not touch; manual mode training in Lightning does not support gradient clipping
save_path: saved/
amp: False

# Data parameters
val_split: 0.05
test_split: 0.01

# Device parameters
devices: auto
num_workers: 8

# Scheduler parameters
loss_monitor: ${scheduler.module_params.loss_monitor}
interval: ${scheduler.module_params.interval}
frequency: ${scheduler.module_params.frequency}
trigger_loss: ${scheduler.module_params.trigger_loss}