defaults:
  - _self_
  - loss: token_pred_vqvae
  - model: token_pred_vqvae
  - learning: ml_vqvae
  - dataset: music_slices

project_name: InfectedBPM
model_name: ml_vqvae_tokenizer
resume: null
use_wandb: false