defaults: 
  - _self_
  - data: lvl1_latent_dllm
  - learning: long
  - loss: dllm
  - model: token_diffusion
  - module: dllm
  - optimizer: adamw_standard
  - scheduler: one_cycle_lr


# Project data
project_name: InfectedPBM
model_name: lvl1_dllm
resume: null

# Optimizations
use_torch_compile: False