defaults: 
  - _self_
  - data: lvl1_vqvae
  - learning: standard
  - loss: ml_vqvae
  - model: ml_vqvae
  - module: music
  - optimizer: adamw_standard
  - scheduler: none


# Project data
project_name: InfectedPBM
model_name: lvl1_vqvae
resume: null

# Optimizations
use_torch_compile: False