defaults: 
  - _self_
  - data: lvl1_latent_dllm
  - learning: standard
  - loss: ml_vqvae
  - model: lvl1_to_lvl2_vqvae
  - module: latent
  - optimizer: adamw_standard
  - scheduler: none


# Project data
project_name: InfectedPBM
model_name: lvl2_vqvae
resume: null

# Optimizations
use_torch_compile: False