defaults:
  - _self_
  - feature_extractor: encoder1d_random_long
  - class_head: mlp_2c

_target_: models.models.discriminator.PatchAttentionDiscriminator
hidden_dim: 128
num_heads: 4
num_layers: 3
dropout: 0.1
patch_size: 16